# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('factualizacion', models.DateTimeField()),
                ('valor_total', models.IntegerField()),
            ],
        ),
    ]
