# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170128_1735'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('valor_total', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
    ]
