# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_movimiento',
            name='slug',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 23, 35, 902043)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 23, 35, 901989)),
        ),
    ]
