# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20171102_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 59, 0, 781258)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 59, 0, 781192)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.proveedor'),
        ),
    ]
