# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181026_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 42, 8, 711069)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 42, 8, 711039)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 42, 8, 712609)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 42, 8, 712484)),
        ),
    ]
