# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20170818_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 12, 5, 3, 624000)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 12, 5, 3, 623000)),
        ),
    ]
