# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20181109_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 43, 44, 746595)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 43, 44, 746565)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 43, 44, 748255)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 19, 43, 44, 748122)),
        ),
    ]
