# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 20:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 39, 8, 96622))),
                ('factualizacion', models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 39, 8, 96653))),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='base.producto')),
            ],
        ),
    ]
