# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 23, 35, 908847)),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 22, 23, 35, 908787)),
        ),
    ]
