# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_proveedor'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.catalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='valor_total',
            field=models.IntegerField(default=0),
        ),
    ]
