# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20170524_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 11, 57, 50, 23000)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 11, 57, 50, 23000)),
        ),
    ]
