# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-26 23:43
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20180202_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 23, 43, 27, 910552)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 23, 43, 27, 910519)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='valor_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='valor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='valor_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
