# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20171102_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 18, 45, 14, 890851)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 18, 45, 14, 890776)),
        ),
    ]
