# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-02 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodegas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('pos_x', models.CharField(max_length=50)),
                ('pos_y', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['orden_ruta']},
        ),
    ]
