# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('nombre_tienda', models.TextField(max_length=20)),
                ('regimen', models.TextField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
