# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170818_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 12, 5, 3, 609000)),
        ),
    ]
