# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170128_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('cedula', models.IntegerField()),
                ('empresa', models.TextField(max_length=20)),
            ],
        ),
    ]
