# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181026_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegas',
            name='direccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bodegas',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bodegas',
            name='telefono',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_tienda',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regimen',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
