# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170312_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10),
        ),
    ]
