# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181109_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cedula',
            field=models.CharField(max_length=45),
        ),
    ]
